--- 
- name: playbook for copying
  hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: copy war file to tomcat server
      copy:
        src: /home/ansible/mini/target/MiniShoppingwebsite.war
        dest: /home/ansible/apache-tomcat-9.0.93/webapps 
